name: Delete Storybook VRT Report

on:
  delete:
    branches-ignore: [main, develop, gh-pages]

concurrency:
  group: ${{ github.event.ref }}
  cancel-in-progress: true

jobs:
  delete-storybook-vrt-report:
    name: Delete Storybook VRT Report
    runs-on: ubuntu-latest
    env:
      BRANCH_REPORTS_DIR: reports/${{ github.event.ref }}
    steps:
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Set Git User
        # see: https://github.com/actions/checkout/issues/13#issuecomment-724415212
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Check for workflow reports
        run: |
          if [ -z "$(ls -A $BRANCH_REPORTS_DIR)" ]; then
            echo "BRANCH_REPORTS_EXIST="false"" >> $GITHUB_ENV
          else
            echo "BRANCH_REPORTS_EXIST="true"" >> $GITHUB_ENV
          fi

      - name: Delete reports from repo for branch
        if: ${{ env.BRANCH_REPORTS_EXIST == 'true' }}
        timeout-minutes: 3
        run: |
          cd $BRANCH_REPORTS_DIR/..

          rm -rf ${{ github.event.ref }}
          git add .
          git commit -m 🔥 レポートを削除 ${{ github.event.ref }}"

          while true; do
            git pull --rebase
            if [ $? -ne 0 ]; then
              echo "rebaseに失敗"
              exit 1
            fi

            git push
            if [ $? -eq 0 ]; then
              echo "削除に成功"
              exit 0
            fi
          done
