# @see https://blog.logto.io/ja/automatic-github-workflow-rerun
name: Rerun workflow

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID'
        required: true
jobs:
  rerun:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: rerun ${{ inputs.run_id }}
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          GH_DEBUG: api
        run: |
          gh run watch ${{ inputs.run_id }} > /dev/null 2>&1
          gh run rerun ${{ inputs.run_id }} --failed
